# Install pre-commit hooks via
# pre-commit install

exclude: >
    (?x)^(
      \.vscode/settings\.json|
      tests/.*xml|
      tests/.*txt|
      src/drain_swamp/\_version\.py|
    )$

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-docstring-first
    - id: check-json
    - id: check-yaml
    - id: debug-statements


  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.18
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.9
    hooks:
      - id: blackdoc
        additional_dependencies: ["black==24.8.0"]
      - id: blackdoc-autoupdate-black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ["--ignore=E704,E203,W503,W605,W293,W291,E501"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
    - id: mypy
      pass_filenames: false
      entry: mypy src/drain_swamp/

  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0  # or master if you're bold
    hooks:
      - id: interrogate
        args: ["-v", "--fail-under=100", "--omit-covered-files"]
        pass_filenames: false  # needed if excluding files with pyproject.toml
